### ISSUE TITLE
After pressing "generate the election" nothing happens

### ISSUE THREAD

**Issue by ghost** [antonio-fr/CivicDapp#1] opened 2016-06-26 17:50 UTC
Hello,

I like the idea for this Dapp very much and therefore I wanted to try it.
But after entering the information (I just typed in "test" everywhere) and than pressing "Generate the election" nothing happens. Do you have any idea why this doesn't work?
P.S.: I tried it with three different browsers and I'm using Win 10.

**Comment by Daboloskov** [comment] 2016-06-26 17:54
Hi there Sebastian,

First of thanks for your interest in Civic.

You'll need to enter (at last) valid testnet address in order to make Civic work. You don't need to use real bitcoins but filling the field with "test" won't work.

Best,

Alex

Le 26 juin 2016 à 19:50, Sebastian K <notifications@github.com<mailto:notifications@github.com>> a écrit :

Hello,

I like the idea for this Dapp very much and therefore I wanted to try it.
But after entering the information (I just typed in "test" everywhere) and than pressing "Generate the election" nothing happens. Do you have any idea why this doesn't work?
P.S.: I tried it with three different browsers and I'm using Win 10.

**Comment by ghost** [comment] 2016-06-26 18:48
Hello Alex,

thanks for reaching out and your fast answer! :) 
Can you give me a bit more guidance where I need to enter the testnet address?
Thank you!

**Comment by Daboloskov** [comment] 2016-06-26 18:54
Ur welcome !

In Setup/index.html

[cid:405AA1F5-55E1-4F65-B28B-1318D67925CE]

In setup 3, fill up a testnet address in "Adresse Votant".

Also I guess you can put any random bitcoin address

Best,

Alex

Le 26 juin 2016 à 20:48, Sebastian K <notifications@github.com<mailto:notifications@github.com>> a écrit :

Hello Alex,

thanks for reaching out and your fast answer! :)
Can you give me a bit more guidance where I need to enter the testnet address?
Thank you!

**Comment by antonio-fr** [comment] 2016-06-26 19:19
Hi Sebastian,

We're happy you enjoy anf test Civic Dapp. Could you send a screenshot shot
with the console for developpers in your browser ? (F12 in Chrome)

I think the main is related to the address of the voters. For testnet you
have to providide Bitcoin address like 1n.. 1m.... Then for the mainnet
with Colu API, you have to provide address of voters or phone phone number.
Be aware that there are regex tests on that point. You can edit in main.js.

Regards, Antoine

Hello,

I like the idea for this Dapp very much and therefore I wanted to try it.
But after entering the information (I just typed in "test" everywhere) and
than pressing "Generate the election" nothing happens. Do you have any idea
why this doesn't work?
P.S.: I tried it with three different browsers and I'm using Win 10.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/antonio-fr/CivicDapp/issues/1, or mute the thread
https://github.com/notifications/unsubscribe/AHM7nTZP6_6AJ6knZqUMTG1uQdPmBnvTks5qPrwBgaJpZM4I-mmJ
.

**Comment by ghost** [comment] 2016-06-26 19:40
Thank you Antoine and Alex!
I tried everything to get it working with the latest release (0.0.5) but it didn't work.
But than I downloaded 0.0.4 and it **worked!** 
I just downloaded 0.0.4, entered two different testnet bitcoin addresses and the magic happened. 
Can't really say what the exact error is but if you want help to reproduce it, I'm really happy to help you. 
Best regards,

Sebastian

**Comment by antonio-fr** [comment] 2016-06-27 00:18
Can you detail if you're using testnet or maimet. Also if you can share
more details about reproducibility and about the bug and the diference btw
0.0.4 & 0.0.5.

Regards,
Antoine

**Comment by antonio-fr** [comment] 2016-06-27 08:29
Some bugs fixed in latest commit

**Closed as completed by antonio-fr** 2016-06-27 08:29 UTC
